-- 코드를 입력하세요
-- SELECT CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Milk' OR NAME LIKE 'Yogurt'GROUP BY CART_ID ORDER BY CART_ID ASC


-- SELECT C.CART_ID FROM (SELECT NAME, CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Milk' OR NAME LIKE 'Yogurt')T JOIN CART_PRODUCTS C ON C.CART_OD=T.CART_ID WHERE COUNT(*)>=1 GROUP BY CART_ID

SELECT A.CART_ID FROM (SELECT COUNT(*) AS CNT, CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Milk' GROUP BY CART_ID) A JOIN (SELECT COUNT(*) AS CNT, CART_ID FROM CART_PRODUCTS WHERE NAME LIKE 'Yogurt' GROUP BY CART_ID) B ON A.CART_ID=B.CART_ID WHERE A.CNT>=1 AND B.CNT>=1 ORDER BY A.CART_ID ASC;