-- 코드를 입력하세요
-- SELECT FROM ONLINE_SALE N JOIN OFFLINE_SALE F

-- SELECT SALES_DATE, PRODUCT_ID,USER_ID,SALES_AMOUNT FROM (SELECT PRODUCT_ID, USER_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE WHERE SALES_DATE LIKE '2022-03-%') UNION (SELECT PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT,SALES_DATE FROM OFFLINE_SALE WHERE SALES_DATE LIKE '2022-03-%')

(SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE WHERE SALES_DATE LIKE '2022-03-%') UNION (SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE LIKE '2022-03-%') ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;

