
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES FROM REST_INFO I JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) R ON I.FAVORITES=R.FAVORITES AND I.FOOD_TYPE=R.FOOD_TYPE ORDER BY FOOD_TYPE DESC
