-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, 
CONCAT(U.CITY,' ', U.STREET_ADDRESS1,' ',U.STREET_ADDRESS2) AS "전체주소",
CONCAT(SUBSTR(U.TLNO, 1, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', SUBSTR(U.TLNO, 8, 4)) AS "전화번호 " 
FROM (SELECT U.USER_ID, COUNT(BOARD_ID) AS CNT FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID=U.USER_ID GROUP BY U.USER_ID) T JOIN USED_GOODS_USER U 
ON T.USER_ID=U.USER_ID 
WHERE T.CNT>=3 
ORDER BY U.USER_ID DESC;