-- 코드를 입력하세요
-- SELECT CAR_ID, CASE WHEN END_DATE<='2022-10-16' THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE GROUP BY CAR_ID ORDER BY CAR_ID DESC; --

-- SELECT C.CAR_ID, T.END_DATE ,'%Y-%m-%D'  FROM (SELECT MAX(END_DATE) AS END_DATE, CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C GROUP BY CAR_ID) T, CAR_RENTAL_COMPANY_RENTAL_HISTORY C WHERE T.CAR_ID=C.CAR_ID ORDER BY CAR_ID DESC;

SELECT CAR_ID, CASE WHEN MAX('2022-10-16' BETWEEN START_DATE AND END_DATE)=1  THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID ORDER BY CAR_ID DESC;