-- 코드를 입력하세요
-- SELECT ID, NAME, HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID)>=2 ORDER BY ID;

SELECT P.ID, P.NAME, P.HOST_ID FROM (SELECT HOST_ID FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID)>=2) T JOIN PLACES P ON T.HOST_ID=P.HOST_ID ORDER BY ID;