-- 코드를 입력하세요
--  SELECT FROM FIRST_HALF F JOIN JULY J

-- (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM FIRST_HALF GROUP BY FLAVOR ORDER BY SUM DESC LIMIT 3)

 -- SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM JULY GROUP BY FLAVOR ORDER BY SUM DESC LIMIT 3
 
 -- SELECT SUM(T1.SUM+T2.SUM) AS SUM, T1.FLAVOR FROM (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM FIRST_HALF) T1 JOIN (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM JULY) T2 ON T1.FLAVOR=T2.FLAVOR GROUP BY FLAVOR ORDER BY SUM DESC LIMIT 3
 
 -- SELECT F.FLAVOR FROM FIRST_HALF F JOIN JULY J ON F.FLAVOR=J.FLAVOR -- GROUP BY F.FLAVOR ORDER BY SUM(F.TOTAL_ORDER+J.TOTAL_ORDER) LIMIT 3;
 
SELECT T1.FLAVOR FROM (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM FIRST_HALF GROUP BY FLAVOR) T1 JOIN (SELECT SUM(TOTAL_ORDER) AS SUM, FLAVOR FROM JULY GROUP BY FLAVOR) T2 ON T1.FLAVOR=T2.FLAVOR GROUP BY FLAVOR ORDER BY SUM(T1.SUM+T2.SUM) DESC LIMIT 3