-- 코드를 입력하세요
-- SELECT FROM(SELECT CAR_ID, COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01' GROUP BY CAR_ID HAVING COUNT(*)>=5) T JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C 

-- SELECT CAR_ID, COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01' GROUP BY CAR_ID HAVING COUNT(*)>=5

SELECT T2.MONTH, T1.CAR_ID,T2.CNT AS RECORDS FROM 
(SELECT CAR_ID, COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01' GROUP BY CAR_ID HAVING COUNT(*)>=5) T1 JOIN
(SELECT COUNT(*) AS CNT,CAR_ID,CASE WHEN START_DATE LIKE '2022-08-%' THEN 8 
WHEN START_DATE LIKE '2022-09-%' THEN 9
WHEN START_DATE LIKE '2022-10-%' THEN 10 
END AS MONTH 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01'
GROUP BY CAR_ID, MONTH HAVING COUNT(*)>=1) T2 ON T1.CAR_ID=T2.CAR_ID
ORDER BY T2.MONTH ASC, T2.CAR_ID DESC;

